import { DayRow } from "@/types/trip";
import { format, parseISO } from "date-fns";

export function buildMarkdownContent(rows: DayRow[], warnings: string[]): string {
  let md = "# Your Trip Itinerary\n\n";
  md += `Generated on ${new Date().toLocaleString()}\n\n`;
  md += "---\n\n";

  // Summary
  if (rows.length > 0) {
    const firstDate = rows[0].date;
    const lastDate = rows[rows.length - 1].date;
    md += `**Trip Duration:** ${firstDate} to ${lastDate} (${rows.length} days)\n\n`;
  }

  // Main itinerary table
  md += "## Daily Itinerary\n\n";

  if (rows.length === 0) {
    md += "*No itinerary data available.*\n\n";
  } else {
    md += "| Date | Day | Lodging | Flights | Car |\n";
    md += "|------|-----|---------|---------|-----|\n";

    rows.forEach((row) => {
      const date = parseISO(row.date);
      const dayName = format(date, "EEE"); // Mon, Tue, etc.
      const dateFormatted = format(date, "MMM d, yyyy"); // Jan 1, 2025

      const hotels = formatColumn(row.hotels);
      const flights = formatColumn(row.flights);
      const cars = formatColumn(row.cars);

      md += `| ${dateFormatted} | ${dayName} | ${hotels} | ${flights} | ${cars} |\n`;
    });

    md += "\n";
  }

  // Warnings section
  md += "## Validation Warnings\n\n";

  if (warnings.length === 0) {
    md += "✅ **None** - Your itinerary looks good!\n\n";
  } else {
    md += "⚠️ **Please review the following:**\n\n";
    warnings.forEach((warning) => {
      md += `- ${warning}\n`;
    });
    md += "\n";
  }

  // Footer
  md += "---\n\n";
  md += "*Generated by Itinera - Your AI Travel Assistant*\n";

  return md;
}


function formatColumn(items?: string[]): string {
  if (!items || items.length === 0) {
    return "-";
  }

  return items.join("<br>");
}
